# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbvdeb',
                'doc_host': 'https://cabra1391.github.io',
                'git_url': 'https://github.com/cabra1391/nbvdeb',
                'lib_path': 'nbvdeb'},
  'syms': {'nbvdeb.core': {'nbvdeb.core.foo': ('core.html#foo', 'nbvdeb/core.py')}}}